### ISSUE TITLE
no commands defined

### ISSUE THREAD

**Issue by llioor** [ufirstgroup/laravel-lang-import-export#1]
I did everything step by step.
The structure is:
resources >> lang >> en >> messages.php

I run this commend:
`php artisan lang-export:csv en_US messages`
or
`php artisan lang-export:csv en messages`

This is the error message:

```
[InvalidArgumentException]
There are no commands defined in the "lang-export" namespace.
```

any idea?

**Comment by llioor** [comment]
@mruoss maybe you can help please?

**Comment by mruoss** [comment]
Hi @llioor 

Do you see the module in the vendor directory? (vendor/ufirst/lang-import-export/)

**Comment by mruoss** [comment]
Alright, please update the module with the code from the current master and try again.

**Comment by llioor** [comment]
Hi @mruoss  Thank you for your response!
When I run this:
`php artisan lang-export:csv --output=storage\app\langs en_US messages`
I receive:

```
[ErrorException]
fopen(storage\app\langs): failed to open stream: Permission denied
```

When I run this:
`php artisan lang-export:csv en_US messages`
I don't receive nothing back and I don't know where the csv is saved?
- I'm doing it on my localhost, running wamp server

Thanks

**Comment by llioor** [comment]
I solved it,
I needed to use full path for artisan commend!

again thanks for the update!
