### ISSUE TITLE
problem with lang-import

### ISSUE THREAD

**Issue by llioor** [ufirstgroup/laravel-lang-import-export#2]
Hi @mruoss, I have exception with lang-import.
I run this commend:
`php \wamp\www\<my-project>\artisan lang-import:csv es messages messages_he.csv`

and I get this exception:

```
[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'UFirst\LangImportExport\Exception' not found
```

Thank you

**Comment by mruoss** [comment]
Yep, that was a bug, I guess. However, the module was actually trying to tell you that it wasn't able to open the language file (at `app_path("lang/{$locale}/{$group}.php")`).

**Comment by llioor** [comment]
The PHP file has to be exist? I was sure it will create the php file for me.

So what you suggest is to create an empty messages.php file and to run it again?

**Comment by mruoss** [comment]
The file should be created if the locale folder exists. Are the permissions correct?

But yeah, you can also try creating a file first...

**Comment by llioor** [comment]
@mruoss  Thanks for answering!

**I created an empty file "messages.php", I run again the comment and I received this error:**

```
php \wamp\www\<my-project>\artisan lang-import:csv es messages messages_he.csv

[ErrorException]
Cannot use a scalar value as an array
```

**So I add:** 
`return [];`
**to the "messages.php" file and then I received this error:**

```
[Exception]
Cannot open language file.
```

**I have "messages.php" and "messages_he.csv" in the current folder.**

**Comment by mruoss** [comment]
What is the current folder? The module was originally written for Laravel 4. It might still use wrong paths...

**Comment by llioor** [comment]
The current folder structure is 
/resources/lang/
/resources/lang/en
/resources/lang/es
/resources/lang/he
/resources/lang/en/messages.php
/resources/lang/en/messages_en.csv

**Comment by mruoss** [comment]
Alright, can you try again with the current master?

**Comment by llioor** [comment]
I still have the same problem... I saw you commit and it is good what you did.

> I created an empty file "messages.php", I run again the comment and I received this error:
> 
> php \wamp\www<my-project>\artisan lang-import:csv es messages messages_he.csv
> 
> [ErrorException]
> Cannot use a scalar value as an array
> So I add: 
> return [];
> to the "messages.php" file and then I received this error:
> 
> [Exception]
> Cannot open language file.
> I have "messages.php" and "messages_he.csv" in the current folder.

**Comment by mruoss** [comment]
Does the user you run the command as have write permissions to messages.php? Pull master again for more infos on the file location.

**Comment by llioor** [comment]
Problem found:

```
 Cannot open language file at C:\wamp\www\2wishu-website\app\resources/lang/
 he/messages.php for writing. Check the file permissions.
```

The app_path() is not correct, please change it to: base_path()

**Comment by mruoss** [comment]
Aaaargh... yes sure. Sorry about that. The resources folder was inside app in Laravel 4. Does it work now?

**Comment by llioor** [comment]
Booom! working! Thank you very much for your help!

When I'm trying to open the generated file with notepad++ everything is working great! But when I'm trying to open it in my editor (netbeans) it tells me that the file is not encoding in UTF-8... can you set the headers to UTF-8?

**Comment by mruoss** [comment]
Well... there are no headers. Is it possible the application you created the CSV with exported non-UTF-8 strings?

**Comment by mruoss** [comment]
Oh and obviousely now you don't have to create empty files anymore in advance ;)

**Comment by llioor** [comment]
Yes I saw it...! thank you very much!

**Comment by llioor** [comment]
> Oh and obviousely now you don't have to create empty files anymore in advance ;)

I still need to create the empty file. Can you add "if not exist, create file"?
